name = "hris-worker"
main = "src/index.ts"
compatibility_date = "2024-10-12"

[[d1_databases]]
binding = "DB"
database_name = "hris_db"
database_id = "eebc5126-6293-47ff-b689-b3403e9baf66"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "hrisunugha"

[vars]
PUBLIC_R2_URL = "https://878529807371894900fa9a38a548bf37.r2.cloudflarestorage.com/hrisunugha"
WAHA_ENDPOINT = "https://waha.unugha.id"
WAHA_SESSION_NAME = "default"
